/**
 * 
 */
package com.ibm.virtualization.ussdactivationweb.reports.service;

import com.ibm.virtualization.ussdactivationweb.utils.Utility;

/**
 * @author Ashad
 *
 */
public class SMSReportConfigInitializer {

	
	 /**
	 *   The file which will have the SMS REPOORT information.
	 */

	public static  String SMS_REPORT_RESOURCE_BUNDLE="com.ibm.virtualization.ussdactivationweb.resources.SMSReport";
	public static  String ALL_SMS_REPORTS="ALL_SMS_REPORTS";
	public static  String NEW_SMS_REPORTS_TYPE="NEW_SMS_REPORTS_TYPE";
	public static  String FIRST_TT="FIRST_TT";
	public static  String SECOND_TT="SECOND_TT";
	public static  String THIRD_TT="THIRD_TT";
	public static  String FIRST_SC="FIRST_SC";
	public static  String SECOND_SC="SECOND_SC";
	public static  String THIRD_SC="THIRD_SC";
	public static  String PENDING="PENDING";
	public static  String SUB_STATUS="SUB_STATUS";
	
	public static String SMS_REPORT_RUN_INTERVAL="SMS_REPORT_RUN_INTERVAL";	
	
	
	
	public static  String ACT_PENDING_AT_DIST_FOR_FTD_FORMAT = "ACT_PENDING_AT_DIST_FOR_FTD_FORMAT";
	public static  String ACT_DONE_AT_DIST_FOR_FTD_FORMAT = "ACT_DONE_AT_DIST_FOR_FTD_FORMAT";
	public static  String ACT_STATUS_FOR_SINGLE_SUB_FORMAT = "ACT_STATUS_FOR_SINGLE_SUB_FORMAT";
	public static  String HUB_WISE_ACT_COUNT_MTD_FORMAT = "HUB_WISE_ACT_COUNT_MTD_FORMAT";
	public static  String HUB_WISE_ACT_COUNT_FOR_FTD_FORMAT = "HUB_WISE_ACT_COUNT_FOR_FTD_FORMAT";
	public static  String CIRCLE_WISE_ACT_COUNT_MTD_FORMAT = "CIRCLE_WISE_ACT_COUNT_MTD_FORMAT";
	public static  String CIRCLE_WISE_ACT_COUNT_FOR_FTD_FORMAT = "CIRCLE_WISE_ACT_COUNT_FOR_FTD_FORMAT";
	public static  String DIST_WISE_ACT_COUNT_FOR_FTD_FORMAT = "DIST_WISE_ACT_COUNT_FOR_FTD_FORMAT";
	public static  String DIST_WISE_ACT_COUNT_MTD_FORMAT = "DIST_WISE_ACT_COUNT_MTD_FORMAT";
	public static  String DEALER_WISE_ACT_COUNT_FOR_FTD_FORMAT = "DEALER_WISE_ACT_COUNT_FOR_FTD_FORMAT";
	public static  String DEALER_WISE_ACT_COUNT_MTD_FORMAT = "DEALER_WISE_ACT_COUNT_MTD_FORMAT";
	public static  String SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD_FORMAT = "SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD_FORMAT";
	public static  String SERVICE_CATEGORY_NAME = "SERVICE_CATEGORY_NAME";
	
	 /**
	 *   The file which will have the NEW SMS REPOORT information.
	 */
	public static  String HUB_TOTAL_SALES="HUB_TOTAL_SALES";
	public static  String HUB_CIRCLE_TOTAL_SALES="HUB_CIRCLE_TOTAL_SALES";
	public static  String CEO_TOTAL_SALES="CEO_TOTAL_SALES";
	public static  String CEO_ZONE_TOTAL_SALES="CEO_ZONE_TOTAL_SALES";
	public static  String CEO_ZBM_TOTAL_SALES="CEO_ZBM_TOTAL_SALES";
	public static  String SH_TOTAL_SALES="SH_TOTAL_SALES";
	public static  String SH_ZBM_TOTAL_SALES="SH_ZBM_TOTAL_SALES";
	public static  String SH_ZONE_TOTAL_SALES="SH_ZONE_TOTAL_SALES";
	public static  String ZBM_TOTAL_SALES="ZBM_TOTAL_SALES";
	public static  String ZBM_ZSM_TOTAL_SALES="ZBM_ZSM_TOTAL_SALES";
	public static  String ZBM_TM_TOTAL_SALES="ZBM_TM_TOTAL_SALES";
	public static  String ZSM_TOTAL_SALES="ZSM_TOTAL_SALES";
	public static  String ZSM_TM_TOTAL_SALES="ZSM_TM_TOTAL_SALES";
	public static  String ZSM_DIST_TOTAL_SALES="ZSM_DIST_TOTAL_SALES";
	public static  String TM_TOTAL_SALES="TM_TOTAL_SALES";
	public static  String TM_DIST_TOTAL_SALES="TM_DIST_TOTAL_SALES";
	public static  String TM_FOS_TOTAL_SALES="TM_FOS_TOTAL_SALES";
	public static  String DIST_TOTAL_SALES="DIST_TOTAL_SALES";
	public static  String DIST_FOS_TOTAL_SALES="DIST_FOS_TOTAL_SALES";
	public static  String DIST_DLR_TOTAL_SALES="DIST_DLR_TOTAL_SALES";
	public static  String FOS_TOTAL_SALES="FOS_TOTAL_SALES";
	public static  String FOS_DLR_TOTAL_SALES="FOS_DLR_TOTAL_SALES";
	public static  String DLR_TOTAL_SALES="DLR_TOTAL_SALES";
	
	
	
	public static  String SC_HUB_TOTAL_SALES="SC_HUB_TOTAL_SALES";
	public static  String SC_HUB_CIRCLE_TOTAL_SALES="SC_HUB_CIRCLE_TOTAL_SALES";
	public static  String SC_CEO_TOTAL_SALES="SC_CEO_TOTAL_SALES";
	public static  String SC_CEO_ZONE_TOTAL_SALES="SC_CEO_ZONE_TOTAL_SALES";
	public static  String SC_CEO_ZBM_TOTAL_SALES="SC_CEO_ZBM_TOTAL_SALES";
	public static  String SC_SH_TOTAL_SALES="SC_SH_TOTAL_SALES";
	public static  String SC_SH_ZBM_TOTAL_SALES="SC_SH_ZBM_TOTAL_SALES";
	public static  String SC_SH_ZONE_TOTAL_SALES="SC_SH_ZONE_TOTAL_SALES";
	public static  String SC_ZBM_TOTAL_SALES="SC_ZBM_TOTAL_SALES";
	public static  String SC_ZBM_ZSM_TOTAL_SALES="SC_ZBM_ZSM_TOTAL_SALES";
	public static  String SC_ZBM_TM_TOTAL_SALES="SC_ZBM_TM_TOTAL_SALES";
	public static  String SC_ZSM_TOTAL_SALES="SC_ZSM_TOTAL_SALES";
	public static  String SC_ZSM_TM_TOTAL_SALES="SC_ZSM_TM_TOTAL_SALES";
	public static  String SC_ZSM_DIST_TOTAL_SALES="SC_ZSM_DIST_TOTAL_SALES";
	public static  String SC_TM_TOTAL_SALES="SC_TM_TOTAL_SALES";
	public static  String SC_TM_DIST_TOTAL_SALES="SC_TM_DIST_TOTAL_SALES";
	public static  String SC_TM_FOS_TOTAL_SALES="SC_TM_FOS_TOTAL_SALES";
	public static  String SC_DIST_TOTAL_SALES="SC_DIST_TOTAL_SALES";
	public static  String SC_DIST_FOS_TOTAL_SALES="SC_DIST_FOS_TOTAL_SALES";
	public static  String SC_DIST_DLR_TOTAL_SALES="SC_DIST_DLR_TOTAL_SALES";
	public static  String SC_FOS_TOTAL_SALES="SC_FOS_TOTAL_SALES";
	public static  String SC_FOS_DLR_TOTAL_SALES="SC_FOS_DLR_TOTAL_SALES";
	public static  String SC_DLR_TOTAL_SALES="SC_DLR_TOTAL_SALES";
	
	public static  String TM_SUBSCRIBER_STATUS="TM_SUBSCRIBER_STATUS";
	public static  String DIST_SUBSCRIBER_STATUS="DIST_SUBSCRIBER_STATUS";
	public static  String FOS_SUBSCRIBER_STATUS="FOS_SUBSCRIBER_STATUS";
	public static  String DLR_SUBSCRIBER_STATUS="DLR_SUBSCRIBER_STATUS";
	
	public static  String TM_PENDING_REPORT="TM_PENDING_REPORT";
	public static  String DIST_PENDING_REPORT="DIST_PENDING_REPORT";
	public static  String FOS_PENDING_REPORT="FOS_PENDING_REPORT";
	
	
	/** SMS Report Code Constants **/
	public static  String ACT_PENDING_AT_DIST_FOR_FTD ="ACT_PENDING_AT_DIST_FOR_FTD";
	public static  String ACT_DONE_AT_DIST_FOR_FTD="ACT_DONE_AT_DIST_FOR_FTD";
	public static  String ACT_STATUS_FOR_SINGLE_SUB="ACT_STATUS_FOR_SINGLE_SUB";
	public static  String HUB_WISE_ACT_COUNT_MTD="HUB_WISE_ACT_COUNT_MTD";
	public static  String HUB_WISE_ACT_COUNT_FOR_FTD="HUB_WISE_ACT_COUNT_FOR_FTD";
	public static  String CIRCLE_WISE_ACT_COUNT_MTD="CIRCLE_WISE_ACT_COUNT_MTD";
	public static  String CIRCLE_WISE_ACT_COUNT_FOR_FTD="CIRCLE_WISE_ACT_COUNT_FOR_FTD";
	public static  String DIST_WISE_ACT_COUNT_FOR_FTD="DIST_WISE_ACT_COUNT_FOR_FTD";	
	public static  String DIST_WISE_ACT_COUNT_MTD="DIST_WISE_ACT_COUNT_MTD";
	public static  String DEALER_WISE_ACT_COUNT_FOR_FTD="DEALER_WISE_ACT_COUNT_FOR_FTD";	
	public static  String DEALER_WISE_ACT_COUNT_MTD="DEALER_WISE_ACT_COUNT_MTD";
	public static  String SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD="SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD";	
	
	/**Latest SMS Report Code Constants **/
	public static  String SERVICE_CLASS_WISE_ACT_COUNT="SERVICE_CLASS_WISE_ACT_COUNT";	
	
	 /**** Validatiom Messages *****/
	public static  String MAX_CIRCLE_CODE_LENGTH ="MAX_CIRCLE_CODE_LENGTH";
	public static  String MIN_MOBILE_NO_LENGTH ="MIN_MOBILE_NO_LENGTH";
	public static  String MAX_MOBILE_NO_LENGTH ="MAX_MOBILE_NO_LENGTH";
	
	public static  String CIRCLE_CODE_ERROR_MESSAGE="CIRCLE_CODE_ERROR_MESSAGE";
	public static  String DIST_REG_NO_LENGTH_ERROR_MSG="DIST_REG_NO_LENGTH_ERROR_MSG";
	public static  String DEALER_REG_NO_LENGTH_ERROR_MSG="DEALER_REG_NO_LENGTH_ERROR_MSG";
	public static  String SUBS_MSISDN_LENGTH_ERROR_MSG="SUBS_MSISDN_LENGTH_ERROR_MSG";
	
	
	public static  String SERVICE_CLASS_ID_ERROR_MSG="SERVICE_CLASS_ID_ERROR_MSG";
	public static  String SERVICE_CLASS_ID_MAX_LENGTH="SERVICE_CLASS_ID_MAX_LENGTH";
	public static  String SERVICE_CLASS_ID_MAX_LENGTH_ERROR_MSG="SERVICE_CLASS_ID_MAX_LENGTH_ERROR_MSG";
	
	public static  String CIRCLE_CODE_LENGTH_ERROR_MESSAGE ="CIRCLE_CODE_LENGTH_ERROR_MESSAGE";

	public static  String DIST_REG_NO_ONLY_NUMERIC_MSG="DIST_REG_NO_ONLY_NUMERIC_MSG";
	public static  String DEALER_REG_NO_ONLY_NUMERIC_MSG="DEALER_REG_NO_ONLY_NUMERIC_MSG";
	public static  String SUBS_MSISDN_ONLY_NUMERIC_MSG="SUBS_MSISDN_ONLY_NUMERIC_MSG";
	public static  String REQUESTOR_MSISDN_ONLY_NUMERIC_MSG="REQUESTOR_MSISDN_ONLY_NUMERIC_MSG";
	public static  String REQUESTOR_REG_NO_LENGTH_ERROR_MSG="REQUESTOR_REG_NO_LENGTH_ERROR_MSG";
	
	
	
	/**
	 *  SMS Report code and SMS Formate message initilized from the SMS Report configuration file.
	 */
	static {
		
		/**  Getting SMS Report Code from SMS Report properies file **/
		ACT_PENDING_AT_DIST_FOR_FTD = Utility.getValueFromBundle(
				ACT_PENDING_AT_DIST_FOR_FTD,SMS_REPORT_RESOURCE_BUNDLE);
		ACT_DONE_AT_DIST_FOR_FTD = Utility.getValueFromBundle(
				ACT_DONE_AT_DIST_FOR_FTD,SMS_REPORT_RESOURCE_BUNDLE);
		ACT_STATUS_FOR_SINGLE_SUB = Utility.getValueFromBundle(
				ACT_STATUS_FOR_SINGLE_SUB,SMS_REPORT_RESOURCE_BUNDLE);
		HUB_WISE_ACT_COUNT_MTD = Utility.getValueFromBundle(
				HUB_WISE_ACT_COUNT_MTD,SMS_REPORT_RESOURCE_BUNDLE);
		HUB_WISE_ACT_COUNT_FOR_FTD = Utility.getValueFromBundle(
				HUB_WISE_ACT_COUNT_FOR_FTD,SMS_REPORT_RESOURCE_BUNDLE);
		CIRCLE_WISE_ACT_COUNT_MTD = Utility.getValueFromBundle(
				CIRCLE_WISE_ACT_COUNT_MTD,SMS_REPORT_RESOURCE_BUNDLE);	
		CIRCLE_WISE_ACT_COUNT_FOR_FTD = Utility.getValueFromBundle(
				CIRCLE_WISE_ACT_COUNT_FOR_FTD,SMS_REPORT_RESOURCE_BUNDLE);
		DIST_WISE_ACT_COUNT_FOR_FTD = Utility.getValueFromBundle(
				DIST_WISE_ACT_COUNT_FOR_FTD,SMS_REPORT_RESOURCE_BUNDLE);
		DIST_WISE_ACT_COUNT_MTD = Utility.getValueFromBundle(
				DIST_WISE_ACT_COUNT_MTD,SMS_REPORT_RESOURCE_BUNDLE);
		DEALER_WISE_ACT_COUNT_FOR_FTD = Utility.getValueFromBundle(
				DEALER_WISE_ACT_COUNT_FOR_FTD,SMS_REPORT_RESOURCE_BUNDLE);
		DEALER_WISE_ACT_COUNT_MTD = Utility.getValueFromBundle(
				DEALER_WISE_ACT_COUNT_MTD,SMS_REPORT_RESOURCE_BUNDLE);
		SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD = Utility.getValueFromBundle(
				SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD,SMS_REPORT_RESOURCE_BUNDLE);
		

		
		
		/**  Getting SMS Report SAPLE format from properies file **/
		
		ALL_SMS_REPORTS = Utility.getValueFromBundle(ALL_SMS_REPORTS,SMS_REPORT_RESOURCE_BUNDLE);
		ACT_DONE_AT_DIST_FOR_FTD_FORMAT = Utility.getValueFromBundle(
				ACT_DONE_AT_DIST_FOR_FTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		ACT_STATUS_FOR_SINGLE_SUB_FORMAT = Utility.getValueFromBundle(
				ACT_STATUS_FOR_SINGLE_SUB_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		HUB_WISE_ACT_COUNT_MTD_FORMAT = Utility.getValueFromBundle(
				HUB_WISE_ACT_COUNT_MTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		HUB_WISE_ACT_COUNT_FOR_FTD_FORMAT = Utility.getValueFromBundle(
				HUB_WISE_ACT_COUNT_FOR_FTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		CIRCLE_WISE_ACT_COUNT_MTD_FORMAT = Utility.getValueFromBundle(
				CIRCLE_WISE_ACT_COUNT_MTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);	
		CIRCLE_WISE_ACT_COUNT_FOR_FTD_FORMAT = Utility.getValueFromBundle(
				CIRCLE_WISE_ACT_COUNT_FOR_FTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		DIST_WISE_ACT_COUNT_FOR_FTD_FORMAT = Utility.getValueFromBundle(
				DIST_WISE_ACT_COUNT_FOR_FTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		DIST_WISE_ACT_COUNT_MTD_FORMAT = Utility.getValueFromBundle(
				DIST_WISE_ACT_COUNT_MTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		DEALER_WISE_ACT_COUNT_FOR_FTD_FORMAT = Utility.getValueFromBundle(
				DEALER_WISE_ACT_COUNT_FOR_FTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		DEALER_WISE_ACT_COUNT_MTD_FORMAT = Utility.getValueFromBundle(
				DEALER_WISE_ACT_COUNT_MTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD_FORMAT = Utility.getValueFromBundle(
				SERVICE_CLASS_WISE_ACT_COUNT_FOR_FTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		ACT_PENDING_AT_DIST_FOR_FTD_FORMAT = Utility.getValueFromBundle(
				ACT_PENDING_AT_DIST_FOR_FTD_FORMAT,SMS_REPORT_RESOURCE_BUNDLE);
		
		/*** validation error messages ***/
		
		CIRCLE_CODE_ERROR_MESSAGE = Utility.getValueFromBundle(
				CIRCLE_CODE_ERROR_MESSAGE,SMS_REPORT_RESOURCE_BUNDLE);
		CIRCLE_CODE_LENGTH_ERROR_MESSAGE = Utility.getValueFromBundle(
				CIRCLE_CODE_LENGTH_ERROR_MESSAGE,SMS_REPORT_RESOURCE_BUNDLE);
		DIST_REG_NO_LENGTH_ERROR_MSG = Utility.getValueFromBundle(
				DIST_REG_NO_LENGTH_ERROR_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		DEALER_REG_NO_LENGTH_ERROR_MSG = Utility.getValueFromBundle(
				DEALER_REG_NO_LENGTH_ERROR_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		SUBS_MSISDN_LENGTH_ERROR_MSG = Utility.getValueFromBundle(
				SUBS_MSISDN_LENGTH_ERROR_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		SERVICE_CLASS_ID_ERROR_MSG = Utility.getValueFromBundle(
				SERVICE_CLASS_ID_ERROR_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		
		SERVICE_CLASS_ID_MAX_LENGTH = Utility.getValueFromBundle(
				SERVICE_CLASS_ID_MAX_LENGTH,SMS_REPORT_RESOURCE_BUNDLE);
		SERVICE_CLASS_ID_MAX_LENGTH_ERROR_MSG = Utility.getValueFromBundle(
				SERVICE_CLASS_ID_MAX_LENGTH_ERROR_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		
		MIN_MOBILE_NO_LENGTH = Utility.getValueFromBundle(
				MIN_MOBILE_NO_LENGTH,SMS_REPORT_RESOURCE_BUNDLE);
		MAX_MOBILE_NO_LENGTH = Utility.getValueFromBundle(
				MAX_MOBILE_NO_LENGTH,SMS_REPORT_RESOURCE_BUNDLE);
		

		DIST_REG_NO_ONLY_NUMERIC_MSG = Utility.getValueFromBundle(
				DIST_REG_NO_ONLY_NUMERIC_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		
		DEALER_REG_NO_ONLY_NUMERIC_MSG = Utility.getValueFromBundle(
				DEALER_REG_NO_ONLY_NUMERIC_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		SUBS_MSISDN_ONLY_NUMERIC_MSG = Utility.getValueFromBundle(
				SUBS_MSISDN_ONLY_NUMERIC_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		
		SERVICE_CATEGORY_NAME = Utility.getValueFromBundle(
				SERVICE_CATEGORY_NAME,SMS_REPORT_RESOURCE_BUNDLE);
		
		REQUESTOR_MSISDN_ONLY_NUMERIC_MSG = Utility.getValueFromBundle(
				REQUESTOR_MSISDN_ONLY_NUMERIC_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		REQUESTOR_REG_NO_LENGTH_ERROR_MSG = Utility.getValueFromBundle(
				REQUESTOR_REG_NO_LENGTH_ERROR_MSG,SMS_REPORT_RESOURCE_BUNDLE);
		
		
		// for new 
		NEW_SMS_REPORTS_TYPE = Utility.getValueFromBundle(
				NEW_SMS_REPORTS_TYPE,SMS_REPORT_RESOURCE_BUNDLE);
		
		SUB_STATUS = Utility.getValueFromBundle(
				SUB_STATUS,SMS_REPORT_RESOURCE_BUNDLE);
		
		PENDING = Utility.getValueFromBundle(
				PENDING,SMS_REPORT_RESOURCE_BUNDLE);
		
		FIRST_TT = Utility.getValueFromBundle(
				FIRST_TT,SMS_REPORT_RESOURCE_BUNDLE);
		
		SECOND_TT = Utility.getValueFromBundle(
				SECOND_TT,SMS_REPORT_RESOURCE_BUNDLE);
		
		THIRD_TT = Utility.getValueFromBundle(
				THIRD_TT,SMS_REPORT_RESOURCE_BUNDLE);
		FIRST_SC = Utility.getValueFromBundle(
				FIRST_SC,SMS_REPORT_RESOURCE_BUNDLE);
		SECOND_SC = Utility.getValueFromBundle(
				SECOND_SC,SMS_REPORT_RESOURCE_BUNDLE);
		THIRD_SC = Utility.getValueFromBundle(
				THIRD_SC,SMS_REPORT_RESOURCE_BUNDLE);
		
		SMS_REPORT_RUN_INTERVAL = Utility.getValueFromBundle(
				SMS_REPORT_RUN_INTERVAL,SMS_REPORT_RESOURCE_BUNDLE);
	}
	
}
